# Generated by Django 4.1.3 on 2022-11-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8')], max_length=10, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.FileField(null=True, upload_to='homepage/pdfs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.ImageField(null=True, upload_to='homepage/covers/'),
        ),
    ]
