# Generated by Django 4.1.3 on 2022-12-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=25, null=True)),
                ('course', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=25, null=True)),
                ('title', models.CharField(max_length=25, null=True)),
                ('subject', models.CharField(max_length=25, null=True)),
                ('profile', models.FileField(null=True, upload_to='homepage/pdfs/')),
                ('course_image', models.ImageField(null=True, upload_to='homepage/covers/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=6, null=True)),
            ],
        ),
    ]
